name: orderable_stack
description: An orderable container widget
version: 0.1.3
homepage: https://github.com/rxlabz/orderable_stack
author: rxlabz <erick@rxla.bz>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  quiver: '^0.28.0'
